server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:order}

  flyway:
    enabled: true
    schemas: ${SPRING_FLYWAY_SCHEMAS:order}
    default-schema: ${SPRING_FLYWAY_DEFAULT_SCHEMA:order}
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

security:
  jwt:
    issuer: ${SECURITY_JWT_ISSUER:connectfood-auth}
    secret: ${SECURITY_JWT_SECRET}

order:
  topics:
    order-created: ${ORDER_TOPICS_ORDER_CREATED:pedido.criado}
