services:
  procpag:
    image: docker.io/erickemprobr/procpag:latest
    platform: linux/amd64
    ports:
      - "8089:8089"
    networks:
      - fase3net

  postgres:
    image: postgres:16-alpine
    container_name: tc3-postgres
    environment:
      POSTGRES_DB: tc3
      POSTGRES_USER: connectfood
      POSTGRES_PASSWORD: connectfood
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fase3net
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    container_name: tc3-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - fase3net
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: tc3-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: fase3-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - fase3net
    restart: unless-stopped

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: tc3-auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tc3
      SPRING_DATASOURCE_USERNAME: connectfood
      SPRING_DATASOURCE_PASSWORD: connectfood

      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: auth
      SPRING_FLYWAY_SCHEMAS: auth
      SPRING_FLYWAY_DEFAULT_SCHEMA: auth

      AUTH_JWT_ISSUER: connectfood-auth
      AUTH_JWT_SECRET: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS"
      AUTH_JWT_ACCESS_TOKEN_TTL_MINUTES: 15
      AUTH_JWT_REFRESH_TOKEN_TTL_DAYS: 7
    depends_on:
      - postgres
    networks:
      - fase3net
    restart: unless-stopped

  order-service:
    build:
      context: ./services/order
      dockerfile: Dockerfile
    container_name: tc3-order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tc3
      SPRING_DATASOURCE_USERNAME: connectfood
      SPRING_DATASOURCE_PASSWORD: connectfood

      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: order
      SPRING_FLYWAY_SCHEMAS: order
      SPRING_FLYWAY_DEFAULT_SCHEMA: order

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ORDER_TOPICS_ORDER_CREATED: pedido.criado

      SECURITY_JWT_ISSUER: connectfood-auth
      SECURITY_JWT_SECRET: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS"
    depends_on:
      - postgres
      - kafka
      - auth-service
    networks:
      - fase3net
    restart: unless-stopped

networks:
  fase3net:

volumes:
  pgdata:
