server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tc3
    username: connectfood
    password: connectfood

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth

  flyway:
    enabled: true
    schemas: auth
    default-schema: auth
    locations: classpath:db/migration

auth:
  jwt:
    issuer: connectfood-auth
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS"
    access-token-ttl-minutes: 15
    refresh-token-ttl-days: 7

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
